version: "3"

services:
  icanfly-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icanfly_server
    ports:
      - "7000:3000"
    restart: always
    env_file:
      - ./.env