version: "3"

services:
  i-can-fly-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: i_can_fly_server
    ports:
      - "6000:3000"
    restart: always
    env_file:
      - ./.env